---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

params:
  stage:

inputs:
  - name: candidate-release
run:
  path: source/ci/tasks/deploy.sh
  args: [
    --input-dir, source
  ]
