---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crdant/serverless-image
    

inputs:
  - name: source

run:
  path: source/ci/tasks/integration.sh
  args: [
    --input-dir, source
  ]
