---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crdant/serverless-image

params:
  stage:

inputs:
  - name: source
  - name: module-cache
  - name: version

outputs:
  - name: archive

run:
  path: source/ci/tasks/package.sh
  args: [
    --input-dir, source,
    --module-cache, module-cache,
    --output-dir, archive,
    --version-file, version/number
  ]
