---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    version: boron

inputs:
  - name: source
  - name: version

outputs:
  - name: archive

run:
  path: source/ci/tasks/package.sh
  args: [
    --input-dir, serverless-package,
    --output-dir, archive,
    --version-file, version/number
  ]
