---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

params:
  aws_access_key_id:
  aws_secret_access_key:
  aws_region:
  twillio_auth_token:
  twillio_account_sid:

inputs:
  - name: source
  - name: version

outputs:
  - name: package

run:
  path: source/ci/tasks/package.sh
  args: [
    --input-dir, source,
    --output-dir, package,
    --version-file, version/number
  ]
