---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crdant/serverless-image

inputs:
  - name: source
  - name: module-cache

run:
  path: source/ci/tasks/unit.sh
  args: [
    --input-dir, source,
    --module-cache, module-cache
  ]
