---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs:
  - name: source
  - name: candidate-release

outputs:
  - name: unpacked

run:
  path: source/ci/tasks/unpack.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, unpacked,
  ]
