# TO DO: add a working directory option that enables a static copy of the source to be available to the entire pipeline

jobs:
  - name: build
    serial_groups: [ version ]
    plan:
      - get: source
        trigger: true
      - get: serverless-resource
        trigger: true
      - get: version
        params: { pre: rc }
      - task: unit-test
        file: source/ci/tasks/unit.yml
      - put: version
        params:
          file: version/number

  - name: package
    serial: true
    plan:
      - get: source
        passed: [build]
      - get: version
        trigger: true
        passed: [ build ]
      - task: package
        file: source/ci/tasks/package.yml
        params:
          base_name: ((application))
          stage: integration
      - task: package
        file: source/ci/tasks/package.yml
        params:
          base_name: ((application))
          stage: production
      - put: candidate-release
        params: { file: archive/((application))-integration-*.tgz }
      - put: candidate-release
        params: { file: archive/((application))-production-*.tgz }

  - name: integration
    serial: true
    plan:
      - get: candidate-release
        trigger: true
        passed: [ package ]
      - get: source
        passed: [ package ]
      - get: version
        passed: [ package ]
      - task: unpack
        file: source/ci/tasks/unpack.yml
        params:
          stage: integration
      - put: serverless-deployment
        params:
          stage: integration
          service: source
          package: unpacked/((application))
      - task: integration-test
        file: source/ci/tasks/integration.yml
        params:
          stage: integration

  - name: ship-it
    serial_groups: [ version ]
    plan:
      - get: candidate-release
        passed: [ integration ]
      - get: source
        passed: [ integration ]
      - get: version
        params: { bump: final }
      - task: unpack
        file: source/ci/tasks/unpack.yml
        params:
          stage: production
      - put: serverless-deployment
        params:
          stage: production
          service: source
          package: unpacked/((application))
      - put: final-release
        params: { file: release/((application))-*.tgz }
      - put: version
        params: { file: version/number }

resources:
  - name: source
    type: git
    source:
      uri: ((github-uri))
      branch: ((github-branch))

  - name: version
    type: semver
    source:
      bucket: ((s3-bucket-version))
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((aws-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: candidate-release
    type: s3
    source:
      bucket: ((s3-bucket-release-candidates))
      regexp: ((application))-(.*).tgz
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((aws-region))
      endpoint: s3.dualstack.((aws-region)).amazonaws.com
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: final-release
    type: s3
    source:
      bucket: ((s3-bucket-releases))
      regexp: ((application))-(.*).tgz
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((aws-region))
      endpoint: s3.dualstack.((aws-region)).amazonaws.com
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: serverless-deployment
    type: serverless
    source:
      aws_access_key_id: ((aws-access-key-id))
      aws_secret_access_key: ((aws-secret-access-key))
      aww_region_name: ((aws-region))

  - name: serverless-resource
    type: docker-image
    source:
      repository: crdant/serverless-resource

resource_types:
  - name: serverless
    type: docker-image
    source:
      repository: crdant/serverless-resource
