resources:
  - name: source
    type: git
    source:
      uri: ((github-uri))
      branch: ((github-branch))

  - name: version
    type: semver
    source:
      bucket: ((s3-bucket-version))
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: ((aws-acccess-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((aws-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: candidate-release
    type: s3
    source:
      bucket: ((s3-bucket-release-candidates))
      regexp: ((application))-(.*).zip
      access_key_id: ((aws-acccess-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((aws-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: final-release
    type: s3
    source:
      bucket: ((s3-bucket-releases))
      regexp: ((application))-(.*).tgz
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
      region_name: ((s3-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

jobs:
  - name: build
    serial_groups: [ version ]
    plan:
      - get: source
        trigger: true
      - get: version
        params: { pre: rc }
      - task: unit-test
        file: source/ci/tasks/unit.yml
      - task: package
        file: source/ci/tasks/package.yml
        params:
          aws_access_key_id: ((aws-acccess-key-id))
          aws_secret_access_key: ((aws-secret-access-key))
          aws_region: ((aws-region))
          twilio_auth_token: ((twilio-auth-token))
          twilio_account_sid: ((twilio-account-sid))
          stage: dev
      - put: candidate-release
        params: { file: package/((application))-*.zip }
      - put: version
        params: { file: version/number }

  - name: integration-test
    serial: true
    plan:
      - get: candidate-release
        trigger: true
        passed: [ build ]
      - get: source
        passed: [ build ]
      - get: version
        passed: [ build ]
      - task: deploy
        file: source/ci/tasks/prepare-integration.yml
        params:
          stage: integration
      # - task: integration-test
      #   file: source/ci/tasks/integration.yml
